"""add coordinates to city

Revision ID: 29b1e4396f8d
Revises: f2cc14ed32bc
Create Date: 2026-01-28 16:32:59.640792

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '29b1e4396f8d'
down_revision: Union[str, Sequence[str], None] = 'f2cc14ed32bc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cities', sa.Column('latitude', sa.Float(), nullable=False))
    op.add_column('cities', sa.Column('longitude', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cities', 'longitude')
    op.drop_column('cities', 'latitude')
    # ### end Alembic commands ###
