"""add recorded_at to temperatures

Revision ID: f2cc14ed32bc
Revises: a8b7def4068b
Create Date: 2026-01-28 16:21:27.479641

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f2cc14ed32bc'
down_revision: Union[str, Sequence[str], None] = 'a8b7def4068b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('temperatures', sa.Column('recorded_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('temperatures', 'recorded_at')
    # ### end Alembic commands ###
